name: advanced_datatable
description: An addition to the Flutter PaginatedDataTable allowing pagination
  also for the datasource aka server side datatables
version: 0.0.9
homepage: https://devowl.de

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  

dev_dependencies:
  test: null
  flutter_test:
    sdk: flutter
  lint: ^2.3.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter: null
